
Simulink.defineIntEnumType( 'Enum_tbm_tbmSts', ...
   {'Init','Watch_for_blowout','Blowout_mitigate', 'Blowout_terminal'}, ...
   [     0                 1               2                3        ], ...
   'DefaultValue', 'Init', ...
   'StorageType', 'uint8', ...
   'AddClassNameToEnumNames', true);


Simulink.defineIntEnumType( 'Enum_tbm_snrType', ...
   {'None', 'Pirelle', 'Sansata', 'Reserved'}, ...
   [     0      1          2          3     ], ...
   'DefaultValue', 'None', ...
   'StorageType', 'uint8', ...
   'AddClassNameToEnumNames', true);
